
services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    hostname: vault
    command: vault server -config=/vault/config/vault.hcl
    ports:
      - "8400:8200"
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_API_ADDR=https://vault:8200
      - VAULT_CLUSTER_ADDR=https://vault:8201
      - VAULT_SKIP_VERIFY=true
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl
      - ./tls:/vault/tls
      - ./data/:/vault/data
      - ./audit/:/var/log/
    cap_add:
      - IPC_LOCK
    restart: unless-stopped


  